// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAs1Shwp2kfi8RyWareYHNY5aOa_6fkg3Q',
    appId: '1:854124715061:web:3939953bdefc19b571257c',
    messagingSenderId: '854124715061',
    projectId: 'cabsud-735c5',
    authDomain: 'cabsud-735c5.firebaseapp.com',
    storageBucket: 'cabsud-735c5.firebasestorage.app',
    measurementId: 'G-8EE8XQHJVV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATzw8_An9DRr0bqoRH8Q-GuhdoA_HPfr8',
    appId: '1:854124715061:android:8862f660d848d60471257c',
    messagingSenderId: '854124715061',
    projectId: 'cabsud-735c5',
    storageBucket: 'cabsud-735c5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA484_jLH-npD_ShPSG4PJE_6dvhbSHtlo',
    appId: '1:854124715061:ios:47207571c1049e6b71257c',
    messagingSenderId: '854124715061',
    projectId: 'cabsud-735c5',
    storageBucket: 'cabsud-735c5.firebasestorage.app',
    iosBundleId: 'com.example.cabsudadminn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA484_jLH-npD_ShPSG4PJE_6dvhbSHtlo',
    appId: '1:854124715061:ios:47207571c1049e6b71257c',
    messagingSenderId: '854124715061',
    projectId: 'cabsud-735c5',
    storageBucket: 'cabsud-735c5.firebasestorage.app',
    iosBundleId: 'com.example.cabsudadminn',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAs1Shwp2kfi8RyWareYHNY5aOa_6fkg3Q',
    appId: '1:854124715061:web:d56ac36c3748ebcf71257c',
    messagingSenderId: '854124715061',
    projectId: 'cabsud-735c5',
    authDomain: 'cabsud-735c5.firebaseapp.com',
    storageBucket: 'cabsud-735c5.firebasestorage.app',
    measurementId: 'G-SF47X94JB5',
  );
}
